# SPDX-FileCopyrightText: 2026 OpenSMI Contributors
#
# SPDX-License-Identifier: MIT

# !!! autogenerated code, do not change manually !!!
# generated on 2026-09-09 11:26:21.497822+02:00

"""Node identifiers from the OPC UA 'Robotics' nodeset. Auto-generated."""

from typing import ClassVar, final

from asyncua import ua

from open_smi_common.frozen import FrozenMeta
from open_smi_common.ua import NodeIdDefinition


@final
class RoboticsNodeIds(metaclass=FrozenMeta):
    """Node identifiers from the OPC UA 'Robotics' nodeset. Auto-generated."""

    FILE_NAME: ClassVar[str] = "Opc.Ua.Robotics.NodeSet2.xml"
    URI: ClassVar[str] = "http://opcfoundation.org/UA/Robotics/"
    VERSION: ClassVar[str] = "1.01.2"
    REQUIRED_URIS: ClassVar[tuple[str, ...]] = ("http://opcfoundation.org/UA/DI/",)

    AuxiliaryComponentType = NodeIdDefinition(URI, ua.Int32(17725))
    AxisMotionProfileEnumeration = NodeIdDefinition(URI, ua.Int32(3008))
    AxisType = NodeIdDefinition(URI, ua.Int32(16601))
    ControllerType = NodeIdDefinition(URI, ua.Int32(1003))
    DriveType = NodeIdDefinition(URI, ua.Int32(17793))
    EmergencyStopFunctionType = NodeIdDefinition(URI, ua.Int32(17230))
    ExecutionModeEnumeration = NodeIdDefinition(URI, ua.Int32(18191))
    GearType = NodeIdDefinition(URI, ua.Int32(1022))
    LoadType = NodeIdDefinition(URI, ua.Int32(1018))
    MotionDeviceCategoryEnumeration = NodeIdDefinition(URI, ua.Int32(18193))
    MotionDeviceSystemType = NodeIdDefinition(URI, ua.Int32(1002))
    MotionDeviceType = NodeIdDefinition(URI, ua.Int32(1004))
    MotorType = NodeIdDefinition(URI, ua.Int32(1019))
    OperationalModeEnumeration = NodeIdDefinition(URI, ua.Int32(3006))
    PowerTrainType = NodeIdDefinition(URI, ua.Int32(16794))
    ProtectiveStopFunctionType = NodeIdDefinition(URI, ua.Int32(17233))
    SafetyStateType = NodeIdDefinition(URI, ua.Int32(1013))
    TaskControlType = NodeIdDefinition(URI, ua.Int32(1011))
    UserType = NodeIdDefinition(URI, ua.Int32(18175))
