# SPDX-FileCopyrightText: 2026 OpenSMI Contributors
#
# SPDX-License-Identifier: MIT

# !!! autogenerated code, do not change manually !!!
# generated on 2026-09-09 11:26:21.547273+02:00

"""Node identifiers from the OPC UA 'RSL' nodeset. Auto-generated."""

from typing import ClassVar, final

from asyncua import ua

from open_smi_common.frozen import FrozenMeta
from open_smi_common.ua import NodeIdDefinition


@final
class RSLNodeIds(metaclass=FrozenMeta):
    """Node identifiers from the OPC UA 'RSL' nodeset. Auto-generated."""

    FILE_NAME: ClassVar[str] = "Opc.Ua.RSL.NodeSet2.xml"
    URI: ClassVar[str] = "http://opcfoundation.org/UA/RSL/"
    VERSION: ClassVar[str] = "1.00.0"
    REQUIRED_URIS: ClassVar[tuple[str, ...]] = ()

    CartesianFrameAngleOrientationType = NodeIdDefinition(URI, ua.Int32(2004))
    RelativeValueType = NodeIdDefinition(URI, ua.Int32(2002))
    RpyOrientationType = NodeIdDefinition(URI, ua.Int32(2005))
    SpatialLocationType = NodeIdDefinition(URI, ua.Int32(2003))
    SpatialObjectType = NodeIdDefinition(URI, ua.Int32(1002))
    SpatialObjectsListType = NodeIdDefinition(URI, ua.Int32(1003))
