# SPDX-FileCopyrightText: 2026 OpenSMI Contributors
#
# SPDX-License-Identifier: MIT

"""Base class for all autogenerated units, see `Unit`."""

from enum import Enum
from typing import Self

from asyncua import ua


class BaseUnit(Enum):
    """Base class for all autogenerated units, see `Unit`."""

    @property
    def symbol(self) -> str:
        """Symbol of the Unit, e.g. ``cm`` for centimeters."""
        return self.value[0]

    @classmethod
    def from_ua_unit_id(cls, ua_unit_id: int) -> Self:
        """Return the unique unit corresponding to given OPC UA unit ID."""
        for unit in cls:
            if unit.ua_unit_id == ua_unit_id:
                return unit

        msg = f"Unknown OPC UA unit ID: {ua_unit_id}"
        raise ValueError(msg)

    @classmethod
    def from_symbol(cls, symbol: str) -> Self:
        """Return the unique unit corresponding to given symbol.

        :raises ValueError: if the symbol is not valid or ambiguous.
        """
        matches = [unit for unit in cls if unit.symbol == symbol]

        if not matches:
            msg = f"Unknown Unit symbol: {symbol}"
            raise ValueError(msg)

        if len(matches) > 1:
            ua_unit_ids = ", ".join(str(unit.ua_unit_id) for unit in matches)
            msg = f"Ambiguous Unit symbol {symbol!r}; unit IDs: {ua_unit_ids}"
            raise ValueError(msg)

        return matches[0]

    @property
    def ua_unit_id(self) -> int:
        """OPC UA Unit ID for the unit."""
        return self.value[1]

    @property
    def ua_eu_information(self) -> ua.EUInformation:
        """Return the OPC UA EU information."""
        return ua.EUInformation(
            NamespaceUri="http://www.opcfoundation.org/UA/units/un/cefact",  # type: ignore
            UnitId=ua.Int32(self.ua_unit_id),  # type: ignore
            DisplayName=ua.LocalizedText(self.symbol),
            Description=ua.LocalizedText(self.name),
        )

    def __str__(self) -> str:
        """Symbol of the Unit."""
        return self.symbol

    def __repr__(self) -> str:
        """Descriptive string representation of the Unit."""
        return f"{type(self).__name__}.{self.name}(symbol={self.symbol!r}, ua_unit_id={self.ua_unit_id!r})"
